# ----------------------------------------------------- 
# --- CYAN FOCUSED PALETTE ---
# ----------------------------------------------------- 

background            #0a0a0a
foreground            #00ffff
selection_foreground  #0a0a0a
selection_background  #00ffff
cursor                #00ffff
cursor_text_color     #0a0a0a

active_border_color    #00ffff
inactive_border_color  #004d4d

color0   #0a0a0a
color8   #555555

color1   #ff005f
color9   #ff5d5d

color2    #008080
color10   #00ffff

color3    #00afaf
color11   #00d7d7

color4   #008787
color12  #00afaf

color5   #005f5f
color13  #008080

color6   #00afaf
color14  #00ffff

color7   #d7ffff
color15  #ffffff
