# ----------------------------------------------------- 
# My Programs
# ----------------------------------------------------- 

$terminal    = kitty
$fileManager = dolphin
$menu        = rofi -show run
$browser     = firefox
$vim         = nvim
$ss          = grim -g "$(slurp)" - | swappy -f -
$awwd        = awww-daemon
$img         = loupe
$awwpaper    = awww img /home/nanoo/Pictures/Wallpapers/wall2.png
