# ----------------------------------------------------- 
# --- PROGRAMS ---
# ----------------------------------------------------- 

$terminal    = kitty
$fileManager = dolphin
$menu        = pkill wofi || wofi --show drun
$powermenu   = ~/.config/wofi/powermenu.sh
$browser     = firefox
$vim         = nvim
$ss          = grim -g "$(slurp)" - | swappy -f -
$img         = loupe
$wallpaper   = hyprpaper
$lock        = hyprlock
$logout      = wlogout
$notify      = dunst
$volume      = pavucontrol
