# ----------------------------------------------------- 
# My Programs
# ----------------------------------------------------- 

$terminal    = kitty
$fileManager = dolphin
$menu        = wofi --show drun
$powermenu   = ~/.config/wofi/powermenu.sh
$browser     = firefox
$vim         = nvim
$ss          = grim -g "$(slurp)" - | swappy -f -
$awwd        = awww-daemon
$img         = loupe
$awwpaper    = hyprpaper
$lock        = hyprlock
$logout      = wlogout
$notify      = dunst
$volume      = pavucontrol
