# ----------------------------------------------------- 
# Window Rules (Modern Syntax)
# ----------------------------------------------------- 

# Ignore maximize requests from all apps
windowrule = suppress_event maximize, match:class .*

# Fix XWayland dragging issues
windowrule = no_focus 1, match:class ^$, match:title ^$, match:xwayland 1, match:floating 1, match:fullscreen 0, match:pinned 0

# Hyprland-run
windowrule = move 20 monitor_h-120, match:class hyprland-run
windowrule = float 1, match:class hyprland-run

# Browser Opacity
windowrule = opaque 1, match:class ^firefox$
windowrule = opaque 1, match:class ^google-chrome$
