# ----------------------------------------------------- 
# --- WINDOW RULES ---
# ----------------------------------------------------- 

# Ignore maximize requests from all apps
windowrule = match:class .*, suppress_event maximize

# Fix XWayland dragging issues
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_focus 1

# Hyprland-run
windowrule = match:class hyprland-run, move 20 monitor_h-120
windowrule = match:class hyprland-run, float 1

# Apps opacity
windowrule = match:class ^firefox$, opaque 1
windowrule = match:class ^code$, opaque 1
